#!/usr/bin/env bash
# Publish the current version as a GitHub release with the zipped app attached.
#
# Run it through `make release`. It refuses to start unless the version can be
# released cleanly, runs the tests, builds and verifies the app, then asks before
# publishing anything. Nothing reaches GitHub until you answer y.
#
# Optional environment:
#   DRAFT=1         create a draft release to review on GitHub first
#   NOTES=file.md   release notes from a file (default: GitHub generates them)
#   TITLE="..."     release title (default: the tag, e.g. v1.2.0)
#   YES=1           skip the confirmation question (for unattended use)

set -euo pipefail
cd "$(dirname "$0")/.."

VERSION=${VERSION:?run this through 'make release'}
ZIP=${ZIP:?run this through 'make release'}
TAG="v$VERSION"
BRANCH=master

die() {
    echo "release: $*" >&2
    exit 1
}

# -- can this version be released? --------------------------------------------
command -v gh >/dev/null || die "the GitHub CLI is not installed: brew install gh"
gh auth status >/dev/null 2>&1 || die "gh is not logged in: run 'gh auth login'"

[ "$(git rev-parse --abbrev-ref HEAD)" = "$BRANCH" ] ||
    die "releases are cut from $BRANCH; you are on $(git rev-parse --abbrev-ref HEAD)"

[ -z "$(git status --porcelain --untracked-files=no)" ] ||
    die "there are uncommitted changes; commit or stash them first"

git fetch --quiet origin "$BRANCH" --tags
[ "$(git rev-parse HEAD)" = "$(git rev-parse "origin/$BRANCH")" ] ||
    die "HEAD is not the same as origin/$BRANCH; push (or pull) first, because the release tags the pushed commit"

if git rev-parse -q --verify "refs/tags/$TAG" >/dev/null; then
    die "the tag $TAG already exists; bump __version__ in receiptscanner/__init__.py"
fi
if git ls-remote --exit-code --tags origin "refs/tags/$TAG" >/dev/null 2>&1; then
    die "the tag $TAG already exists on GitHub; bump __version__ in receiptscanner/__init__.py"
fi
if [ -n "${NOTES:-}" ] && [ ! -f "$NOTES" ]; then
    die "NOTES file not found: $NOTES"
fi

echo "Releasing $TAG from $(git rev-parse --short HEAD) on $BRANCH"

# -- prove it works, then package it ------------------------------------------
make test build verify package
[ -f "$ZIP" ] || die "expected $ZIP but it was not produced"

echo
echo "Ready to publish:"
echo "  tag      $TAG  ->  $(git rev-parse --short HEAD)"
echo "  asset    $(basename "$ZIP")  ($(du -h "$ZIP" | cut -f1))"
echo "  notes    ${NOTES:-generated by GitHub}"
if [ "${DRAFT:-}" = "1" ]; then
    echo "  mode     draft (not public until you publish it on GitHub)"
fi

if [ "${YES:-}" != "1" ]; then
    read -r -p "Publish $TAG to GitHub? [y/N] " reply
    case "$reply" in
    y | Y) ;;
    *) die "cancelled; nothing was published" ;;
    esac
fi

# -- publish ------------------------------------------------------------------
args=("$TAG" "$ZIP" --target "$(git rev-parse HEAD)" --title "${TITLE:-$TAG}")
if [ -n "${NOTES:-}" ]; then
    args+=(--notes-file "$NOTES")
else
    args+=(--generate-notes)
fi
if [ "${DRAFT:-}" = "1" ]; then
    args+=(--draft)
fi

gh release create "${args[@]}"
git fetch --quiet origin --tags
echo "Published $TAG"
